# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ports.xdc

# Block Designs: bd/vga_block/vga_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_block || ORIG_REF_NAME==vga_block}]

# IP: bd/vga_block/ip/vga_block_blk_mem_gen_0_0/vga_block_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_block_blk_mem_gen_0_0 || ORIG_REF_NAME==vga_block_blk_mem_gen_0_0}]

# Block Designs: bd/clk/clk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk || ORIG_REF_NAME==clk}]

# IP: bd/clk/ip/clk_clk_wiz_0_0_1/clk_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_clk_wiz_0_0 || ORIG_REF_NAME==clk_clk_wiz_0_0}]

# XDC: bd/vga_block/vga_block_ooc.xdc

# XDC: bd/clk/clk_ooc.xdc
