# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ASUS/Desktop/ceshi/1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/Desktop/ceshi/1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/vga_block/hdl/vga_block_wrapper.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/sccb_sender.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/cfg_regs.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/imports/hdl/CLK_wrapper.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/vga_dpram.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/my_vga_syn.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/debounce.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/cfg_ov.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/CAPTURE.v
  C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/new/OV7670_TOP.v
}
add_files C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/vga_block/vga_block.bd
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/vga_block/ip/vga_block_blk_mem_gen_0_0/vga_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/vga_block/vga_block_ooc.xdc]
set_property is_locked true [get_files C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/vga_block/vga_block.bd]

add_files C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/clk/clk.bd
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_0_1/clk_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_0_1/clk_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_0_1/clk_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/clk/clk_ooc.xdc]
set_property is_locked true [get_files C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/sources_1/bd/clk/clk.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/constrs_3/new/ports.xdc
set_property used_in_implementation false [get_files C:/Users/ASUS/Desktop/ceshi/1/project_1.srcs/constrs_3/new/ports.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top OV7670_VGA_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef OV7670_VGA_TOP.dcp

catch { report_utilization -file OV7670_VGA_TOP_utilization_synth.rpt -pb OV7670_VGA_TOP_utilization_synth.pb }
